#!/usr/bin/env sh

echo "Installing packages with homebrew"
brew install \
  age \
  bat \
  eza \
  fd \
  font-hack font-hack-nerd-font \
  fzf \
  git-delta \
  imagemagick \
  jandedobbeleer/oh-my-posh/oh-my-posh \
  jesseduffield/lazydocker/lazydocker \
  jesseduffield/lazygit/lazygit \
  jq \
  miller \
  p7zip \
  ripgrep \
  rom-tools \
  tmux \
  vivid \
  watch \
  wget \
  xdelta \
  zoxide
